" meow-dark Vim color scheme generated by meowtheme.
highlight clear
if exists('syntax_on')
  syntax reset
endif
set background=dark
let g:colors_name = 'meow-dark'

highlight Normal guifg=#d1d3d4 guibg=#0f0e12
highlight ColorColumn guibg=#252428
highlight Conceal guifg=#484850
highlight Cursor guifg=#0f0e12 guibg=#238dc1
highlight CursorLine guibg=#1a191d
highlight CursorLineNr guifg=#d1d3d4
highlight Directory guifg=#238dc1
highlight Error guifg=#ca003d guibg=#1a191d
highlight FoldColumn guifg=#484850 guibg=#0f0e12
highlight Folded guifg=#b2b2b2 guibg=#1a191d
highlight LineNr guifg=#484850
highlight MatchParen guifg=#d1d3d4 guibg=#252428
highlight NonText guifg=#484850
highlight Pmenu guifg=#d1d3d4 guibg=#1a191d
highlight PmenuSel guifg=#d1d3d4 guibg=#252428
highlight Search guifg=#d1d3d4 guibg=#252428
highlight SignColumn guibg=#0f0e12
highlight StatusLine guifg=#d1d3d4 guibg=#1a191d
highlight StatusLineNC guifg=#b2b2b2 guibg=#1a191d
highlight VertSplit guifg=#252428
highlight Visual guibg=#252428
highlight WarningMsg guifg=#fbb410
highlight Comment guifg=#484850 gui=italic
highlight Constant guifg=#e55022
highlight String guifg=#008556
highlight Character guifg=#008556
highlight Number guifg=#e55022
highlight Boolean guifg=#e55022
highlight Float guifg=#e55022
highlight Identifier guifg=#d1d3d4
highlight Function guifg=#238dc1
highlight Statement guifg=#a256b3
highlight Conditional guifg=#a256b3
highlight Repeat guifg=#a256b3
highlight Label guifg=#a256b3
highlight Operator guifg=#d1d3d4
highlight Keyword guifg=#a256b3
highlight Exception guifg=#a256b3
highlight PreProc guifg=#00ade3
highlight Include guifg=#a256b3
highlight Define guifg=#a256b3
highlight Macro guifg=#00ade3
highlight PreCondit guifg=#00ade3
highlight Type guifg=#fbb410
highlight StorageClass guifg=#a256b3
highlight Structure guifg=#fbb410
highlight Typedef guifg=#fbb410
highlight Special guifg=#00ade3
highlight SpecialChar guifg=#008556
highlight Tag guifg=#00ade3
highlight Delimiter guifg=#d1d3d4
highlight SpecialComment guifg=#484850 gui=italic
highlight Debug guifg=#ca003d
highlight Underlined guifg=#238dc1 gui=underline
highlight Ignore guifg=#484850
highlight ErrorMsg guifg=#ca003d
highlight Todo guifg=#fbb410 guibg=#1a191d
highlight DiffAdd guifg=#008556 guibg=#1a191d
highlight DiffChange guifg=#238dc1 guibg=#1a191d
highlight DiffDelete guifg=#ca003d guibg=#1a191d
highlight DiffText guifg=#238dc1 guibg=#1a191d
