" meow-light Vim color scheme generated by meowtheme.
highlight clear
if exists('syntax_on')
  syntax reset
endif
set background=light
let g:colors_name = 'meow-light'

highlight Normal guifg=#252428 guibg=#f1f2f2
highlight ColorColumn guibg=#d1d3d4
highlight Conceal guifg=#b2b2b2
highlight Cursor guifg=#f1f2f2 guibg=#238dc1
highlight CursorLine guibg=#e5e5e5
highlight CursorLineNr guifg=#252428
highlight Directory guifg=#238dc1
highlight Error guifg=#ca003d guibg=#e5e5e5
highlight FoldColumn guifg=#b2b2b2 guibg=#f1f2f2
highlight Folded guifg=#484850 guibg=#e5e5e5
highlight LineNr guifg=#b2b2b2
highlight MatchParen guifg=#252428 guibg=#d1d3d4
highlight NonText guifg=#b2b2b2
highlight Pmenu guifg=#252428 guibg=#e5e5e5
highlight PmenuSel guifg=#252428 guibg=#d1d3d4
highlight Search guifg=#252428 guibg=#d1d3d4
highlight SignColumn guibg=#f1f2f2
highlight StatusLine guifg=#252428 guibg=#e5e5e5
highlight StatusLineNC guifg=#484850 guibg=#e5e5e5
highlight VertSplit guifg=#d1d3d4
highlight Visual guibg=#d1d3d4
highlight WarningMsg guifg=#fbb410
highlight Comment guifg=#b2b2b2 gui=italic
highlight Constant guifg=#e55022
highlight String guifg=#008556
highlight Character guifg=#008556
highlight Number guifg=#e55022
highlight Boolean guifg=#e55022
highlight Float guifg=#e55022
highlight Identifier guifg=#252428
highlight Function guifg=#238dc1
highlight Statement guifg=#a256b3
highlight Conditional guifg=#a256b3
highlight Repeat guifg=#a256b3
highlight Label guifg=#a256b3
highlight Operator guifg=#252428
highlight Keyword guifg=#a256b3
highlight Exception guifg=#a256b3
highlight PreProc guifg=#00ade3
highlight Include guifg=#a256b3
highlight Define guifg=#a256b3
highlight Macro guifg=#00ade3
highlight PreCondit guifg=#00ade3
highlight Type guifg=#8a673b
highlight StorageClass guifg=#a256b3
highlight Structure guifg=#8a673b
highlight Typedef guifg=#8a673b
highlight Special guifg=#00ade3
highlight SpecialChar guifg=#008556
highlight Tag guifg=#00ade3
highlight Delimiter guifg=#252428
highlight SpecialComment guifg=#b2b2b2 gui=italic
highlight Debug guifg=#ca003d
highlight Underlined guifg=#238dc1 gui=underline
highlight Ignore guifg=#b2b2b2
highlight ErrorMsg guifg=#ca003d
highlight Todo guifg=#fbb410 guibg=#e5e5e5
highlight DiffAdd guifg=#008556 guibg=#e5e5e5
highlight DiffChange guifg=#238dc1 guibg=#e5e5e5
highlight DiffDelete guifg=#ca003d guibg=#e5e5e5
highlight DiffText guifg=#238dc1 guibg=#e5e5e5
