from __future__ import annotations

from meowtheme.base16 import Base16Palette
from meowtheme.renderers.common import semantic_tokens


def render_ghostty(palette: Base16Palette) -> str:
    tokens = semantic_tokens(palette)
    palette_colors = {
        0: tokens["surface"],
        1: tokens["red"],
        2: tokens["green"],
        3: tokens["yellow"],
        4: tokens["blue"],
        5: tokens["purple"],
        6: tokens["cyan"],
        7: tokens["foreground"],
        8: tokens["muted"],
        9: tokens["red"],
        10: tokens["green"],
        11: tokens["yellow"],
        12: tokens["blue"],
        13: tokens["purple"],
        14: tokens["cyan"],
        15: tokens["foregroundBright"],
    }
    lines = [
        f"# {palette.scheme} Ghostty theme generated by meowtheme",
        f"background = {tokens['background']}",
        f"foreground = {tokens['foreground']}",
        f"cursor-color = {tokens['foreground']}",
        f"cursor-text = {tokens['background']}",
        f"selection-background = {tokens['surfaceRaised']}",
        f"selection-foreground = {tokens['foreground']}",
    ]
    lines.extend(f"palette = {index}={color}" for index, color in palette_colors.items())
    return "\n".join(lines) + "\n"
