from __future__ import annotations

from meowtheme.base16 import Base16Palette
from meowtheme.renderers.common import pretty_json
from meowtheme.renderers.editor_colors import editor_colors


def render_zed(palette: Base16Palette) -> str:
    colors = editor_colors(palette)
    syntax = {
        "attribute": {"color": colors.syntax.attribute},
        "boolean": {"color": colors.syntax.boolean},
        "comment": {"color": colors.syntax.comment, "font_style": "italic"},
        "constant": {"color": colors.syntax.constant},
        "constructor": {"color": colors.syntax.constructor},
        "emphasis": {"color": colors.syntax.function, "font_style": "italic"},
        "emphasis.markup": {"color": colors.syntax.function, "font_style": "italic"},
        "emphasis.strong": {"color": colors.syntax.type, "font_weight": 700},
        "emphasis.strong.markup": {"color": colors.syntax.type, "font_weight": 700},
        "function": {"color": colors.syntax.function},
        "keyword": {"color": colors.syntax.keyword},
        "link_text": {"color": colors.syntax.function, "font_style": "italic"},
        "link_text.markup": {"color": colors.syntax.function, "font_style": "italic"},
        "link_uri": {"color": colors.syntax.property},
        "link_uri.markup": {"color": colors.syntax.property},
        "number": {"color": colors.syntax.number},
        "property": {"color": colors.syntax.property},
        "punctuation": {"color": colors.syntax.punctuation},
        "string": {"color": colors.syntax.string},
        "strikethrough": {"color": colors.syntax.comment},
        "strikethrough.markup": {"color": colors.syntax.comment},
        "text.literal": {"color": colors.syntax.string},
        "text.literal.markup": {"color": colors.syntax.string},
        "title": {"color": colors.syntax.function, "font_weight": 700},
        "title.markup": {"color": colors.syntax.function, "font_weight": 700},
        "type": {"color": colors.syntax.type},
        "variable": {"color": colors.syntax.variable},
    }
    style = {
        "accents": colors.accents,
        "background": colors.background,
        "border": colors.border,
        "border.focused": colors.border_focused,
        "border.selected": colors.border_selected,
        "border.variant": colors.border_variant,
        "conflict": colors.conflict.foreground,
        "conflict.background": colors.conflict.background,
        "conflict.border": colors.conflict.border,
        "created": colors.created.foreground,
        "created.background": colors.created.background,
        "created.border": colors.created.border,
        "deleted": colors.deleted.foreground,
        "deleted.background": colors.deleted.background,
        "deleted.border": colors.deleted.border,
        "editor.active_line.background": colors.editor_active_line_background,
        "editor.active_line_number": colors.editor_active_line_number,
        "editor.active_wrap_guide": colors.editor_active_wrap_guide,
        "editor.background": colors.editor_background,
        "editor.document_highlight.read_background": colors.editor_document_highlight_read_background,
        "editor.document_highlight.write_background": colors.editor_document_highlight_write_background,
        "editor.foreground": colors.editor_foreground,
        "editor.gutter.background": colors.editor_gutter_background,
        "editor.highlighted_line.background": colors.editor_highlighted_line_background,
        "editor.indent_guide": colors.editor_indent_guide,
        "editor.indent_guide_active": colors.editor_indent_guide_active,
        "editor.invisible": colors.editor_invisible,
        "editor.line_number": colors.editor_line_number,
        "editor.subheader.background": colors.editor_subheader_background,
        "editor.wrap_guide": colors.editor_wrap_guide,
        "element.active": colors.element_active,
        "element.background": colors.element_background,
        "element.disabled": colors.element_disabled,
        "element.hover": colors.element_hover,
        "element.selected": colors.element_selected,
        "elevated_surface.background": colors.elevated_surface_background,
        "error": colors.error.foreground,
        "error.background": colors.error.background,
        "error.border": colors.error.border,
        "ghost_element.active": colors.ghost_element_active,
        "ghost_element.background": colors.ghost_element_background,
        "ghost_element.disabled": colors.ghost_element_disabled,
        "ghost_element.hover": colors.ghost_element_hover,
        "ghost_element.selected": colors.ghost_element_selected,
        "hint": colors.hint.foreground,
        "hint.background": colors.hint.background,
        "hint.border": colors.hint.border,
        "icon": colors.icon,
        "icon.accent": colors.icon_accent,
        "icon.disabled": colors.icon_disabled,
        "icon.muted": colors.icon_muted,
        "icon.placeholder": colors.icon_placeholder,
        "info": colors.info.foreground,
        "info.background": colors.info.background,
        "info.border": colors.info.border,
        "link_text.hover": colors.link_text_hover,
        "modified": colors.modified.foreground,
        "modified.background": colors.modified.background,
        "modified.border": colors.modified.border,
        "pane.focused_border": colors.pane_focused_border,
        "pane_group.border": colors.pane_group_border,
        "panel.background": colors.panel_background,
        "panel.focused_border": colors.panel_focused_border,
        "panel.indent_guide": colors.panel_indent_guide,
        "panel.indent_guide_active": colors.panel_indent_guide_active,
        "panel.indent_guide_hover": colors.panel_indent_guide_hover,
        "players": [
            {
                "background": colors.player_background,
                "cursor": colors.player_cursor,
                "selection": colors.player_selection,
            }
        ],
        "renamed": colors.renamed.foreground,
        "renamed.background": colors.renamed.background,
        "renamed.border": colors.renamed.border,
        "scrollbar.thumb.background": colors.scrollbar_thumb_background,
        "scrollbar.thumb.border": colors.scrollbar_thumb_border,
        "scrollbar.thumb.hover_background": colors.scrollbar_thumb_hover_background,
        "scrollbar.track.background": colors.scrollbar_track_background,
        "scrollbar.track.border": colors.scrollbar_track_border,
        "search.match_background": colors.search_match_background,
        "status_bar.background": colors.status_bar_background,
        "success": colors.success.foreground,
        "success.background": colors.success.background,
        "success.border": colors.success.border,
        "surface.background": colors.surface_background,
        "syntax": syntax,
        "tab.active_background": colors.tab_active_background,
        "tab.inactive_background": colors.tab_inactive_background,
        "tab_bar.background": colors.tab_bar_background,
        "terminal.ansi.background": colors.terminal.ansi_background,
        "terminal.ansi.black": colors.terminal.ansi_black,
        "terminal.ansi.blue": colors.terminal.ansi_blue,
        "terminal.ansi.bright_black": colors.terminal.ansi_bright_black,
        "terminal.ansi.bright_blue": colors.terminal.ansi_bright_blue,
        "terminal.ansi.bright_cyan": colors.terminal.ansi_bright_cyan,
        "terminal.ansi.bright_green": colors.terminal.ansi_bright_green,
        "terminal.ansi.bright_magenta": colors.terminal.ansi_bright_magenta,
        "terminal.ansi.bright_red": colors.terminal.ansi_bright_red,
        "terminal.ansi.bright_white": colors.terminal.ansi_bright_white,
        "terminal.ansi.bright_yellow": colors.terminal.ansi_bright_yellow,
        "terminal.ansi.cyan": colors.terminal.ansi_cyan,
        "terminal.ansi.dim_black": colors.terminal.ansi_dim_black,
        "terminal.ansi.dim_blue": colors.terminal.ansi_dim_blue,
        "terminal.ansi.dim_cyan": colors.terminal.ansi_dim_cyan,
        "terminal.ansi.dim_green": colors.terminal.ansi_dim_green,
        "terminal.ansi.dim_magenta": colors.terminal.ansi_dim_magenta,
        "terminal.ansi.dim_red": colors.terminal.ansi_dim_red,
        "terminal.ansi.dim_white": colors.terminal.ansi_dim_white,
        "terminal.ansi.dim_yellow": colors.terminal.ansi_dim_yellow,
        "terminal.ansi.green": colors.terminal.ansi_green,
        "terminal.ansi.magenta": colors.terminal.ansi_magenta,
        "terminal.ansi.red": colors.terminal.ansi_red,
        "terminal.ansi.white": colors.terminal.ansi_white,
        "terminal.ansi.yellow": colors.terminal.ansi_yellow,
        "terminal.background": colors.terminal.background,
        "terminal.bright_foreground": colors.terminal.bright_foreground,
        "terminal.dim_foreground": colors.terminal.dim_foreground,
        "terminal.foreground": colors.terminal.foreground,
        "text": colors.text,
        "text.accent": colors.text_accent,
        "text.disabled": colors.text_disabled,
        "text.muted": colors.text_muted,
        "text.placeholder": colors.text_placeholder,
        "title_bar.background": colors.title_bar_background,
        "title_bar.inactive_background": colors.title_bar_inactive_background,
        "toolbar.background": colors.toolbar_background,
        "warning": colors.warning.foreground,
        "warning.background": colors.warning.background,
        "warning.border": colors.warning.border,
    }
    payload = {
        "name": palette.scheme,
        "author": palette.author,
        "themes": [
            {
                "name": palette.scheme,
                "appearance": palette.appearance,
                "style": style,
            }
        ],
    }
    return pretty_json(payload)
